many tries to make zxing work but now i'm getting this:
java.lang.RuntimeException: Unable to start activity
ComponentInfo{totalcross.android/totalcross.android.CaptureActivity}:
android.view.InflateException: Binary XML file line #17: Error inflating
class alpha
09-12 16:31:46.982 E/AndroidRuntime(32388):     at
android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3184)
09-12 16:31:46.982 E/AndroidRuntime(32388):     at
android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3294)
09-12 16:31:46.982 E/AndroidRuntime(32388):     at
android.app.ActivityThread.access$1000(ActivityThread.java:210)
09-12 16:31:46.982 E/AndroidRuntime(32388):     at
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1704)
09-12 16:31:46.982 E/AndroidRuntime(32388):     at
android.os.Handler.dispatchMessage(Handler.java:102)
09-12 16:31:46.982 E/AndroidRuntime(32388):     at
android.os.Looper.loop(Looper.java:145)
09-12 16:31:46.982 E/AndroidRuntime(32388):     at
android.app.ActivityThread.main(ActivityThread.java:6938)
09-12 16:31:46.982 E/AndroidRuntime(32388):     at
java.lang.reflect.Method.invoke(Native Method)
09-12 16:31:46.982 E/AndroidRuntime(32388):     at
java.lang.reflect.Method.invoke(Method.java:372)
09-12 16:31:46.982 E/AndroidRuntime(32388):     at
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
09-12 16:31:46.982 E/AndroidRuntime(32388):     at
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
09-12 16:31:46.982 E/AndroidRuntime(32388): Caused by:
android.view.InflateException: Binary XML file line #17: Error inflating
class alpha
09-12 16:31:46.982 E/AndroidRuntime(32388):     at
android.preference.GenericInflater.createItemFromTag(GenericInflater.java:441)
09-12 16:31:46.982 E/AndroidRuntime(32388):     at
android.preference.GenericInflater.inflate(GenericInflater.java:317)
09-12 16:31:46.982 E/AndroidRuntime(32388):     at
android.preference.GenericInflater.inflate(GenericInflater.java:263)
09-12 16:31:46.982 E/AndroidRuntime(32388):     at
android.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:272)
09-12 16:31:46.982 E/AndroidRuntime(32388):     at
android.preference.PreferenceManager.setDefaultValues(PreferenceManager.java:485)
09-12 16:31:46.982 E/AndroidRuntime(32388):     at
android.preference.PreferenceManager.setDefaultValues(PreferenceManager.java:444)
09-12 16:31:46.982 E/AndroidRuntime(32388):     at
totalcross.android.CaptureActivity.onCreate(CaptureActivity.java:146)
09-12 16:31:46.982 E/AndroidRuntime(32388):     at
android.app.Activity.performCreate(Activity.java:6575)
09-12 16:31:46.982 E/AndroidRuntime(32388):     at
android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1134)
09-12 16:31:46.982 E/AndroidRuntime(32388):     at
android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3137)
09-12 16:31:46.982 E/AndroidRuntime(32388):     ... 10 more
09-12 16:31:46.982 E/AndroidRuntime(32388): Caused by:
java.lang.ClassNotFoundException: Didn't find class
"android.preference.alpha" on path: DexPathList[[zip file
"/system/framework/com.google.android.maps.jar", zip file
"/data/app/totalcross.android-2/base.apk"],nativeLibraryDirectories=[/data/app/totalcross.android-2/lib/arm,
/vendor/lib, /system/lib]]
09-12 16:31:46.982 E/AndroidRuntime(32388):     at
dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
09-12 16:31:46.982 E/AndroidRuntime(32388):     at
java.lang.ClassLoader.loadClass(ClassLoader.java:511)
09-12 16:31:46.982 E/AndroidRuntime(32388):     at
java.lang.ClassLoader.loadClass(ClassLoader.java:469)
09-12 16:31:46.982 E/AndroidRuntime(32388):     at
android.preference.GenericInflater.createItem(GenericInflater.java:375)
09-12 16:31:46.982 E/AndroidRuntime(32388):     at
android.preference.GenericInflater.onCreateItem(GenericInflater.java:417)
09-12 16:31:46.982 E/AndroidRuntime(32388):     at
android.preference.GenericInflater.createItemFromTag(GenericInflater.java:428)
09-12 16:31:46.982 E/AndroidRuntime(32388):     ... 19 more
09-12 16:31:46.982 E/AndroidRuntime(32388):     Suppressed:
java.lang.ClassNotFoundException: android.preference.alpha
09-12 16:31:46.982 E/AndroidRuntime(32388):             at
java.lang.Class.classForName(Native Method)
09-12 16:31:46.982 E/AndroidRuntime(32388):             at
java.lang.BootClassLoader.findClass(ClassLoader.java:781)
09-12 16:31:46.982 E/AndroidRuntime(32388):             at
java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
09-12 16:31:46.982 E/AndroidRuntime(32388):             at
java.lang.ClassLoader.loadClass(ClassLoader.java:504)
09-12 16:31:46.982 E/AndroidRuntime(32388):             ... 23 more
09-12 16:31:46.982 E/AndroidRuntime(32388):     Caused by:
java.lang.NoClassDefFoundError: Class not found using the boot class
loader; no stack available